version: 2.1
orbs:
  node: circleci/node@1.1.6
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-test:
    working_directory: ~/angular-ecommerce
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-ecommerce-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - run: yarn install
      - save_cache:
          key: angular-ecommerce-{{ .Branch }}-{{ checksum "yarn.lock"}}
          paths:
            - "nodes_modules"
      - run: yarn run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: yarn run build
      - deploy:
          command: |
            ./node_modules/.bin/surge --project ~/angular-ecommerce/dist/real-world --domain angular-ecommerce-fake-api-dev.surge.sh
workflows:
    build-and-test:
      jobs:
        - build-and-test
